spring:
  config:
    activate:
      on-profile: default
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test;MODE=MYSQL'
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: none

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
---
