spring:
  config:
    activate:
      on-profile: default
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test;MODE=MYSQL'
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: none
        default_batch_fetch_size: 30
        jdbc.batch_size: 30
        hibernate.physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.SQL: DEBUG

---
