name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DICTIONARY_API_KEY: ${{ secrets.DICTIONARY_API_KEY }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set Date Variable
        run: echo "CURRENT_DATE=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew build

      - name: Deploy to EC2
        env:
          KEY_FILE: key.pem
          EC2_INSTANCE: ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_PUBLIC_IP }}
          SOURCE_DIR: build/libs/word-puzzle.jar
          LIB_DIR: /home/${{ secrets.EC2_USERNAME }}/libs/word-puzzle-${{ env.CURRENT_DATE }}.jar
          LOG_DIR: /home/${{ secrets.EC2_USERNAME }}/logs/word-puzzle-${{ env.CURRENT_DATE }}.log
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > $KEY_FILE
          chmod 600 $KEY_FILE
          scp -i $KEY_FILE -o StrictHostKeyChecking=no $SOURCE_DIR $EC2_INSTANCE:$LIB_DIR
          ssh -i $KEY_FILE -o StrictHostKeyChecking=no $EC2_INSTANCE "pgrep java | xargs kill -9; nohup java -jar $LIB_DIR > $LOG_DIR 2>&1 &"
          rm -f $KEY_FILE